Add webpack-dev-server
growthbook/devtools pull request #14
Opened 2023-03-09 20:55 UTC by bttf

It works

## It working
<img width="1582" alt="Screenshot 2023-03-09 at 3 51 15 PM" src="https://user-images.githubusercontent.com/2374625/224155566-f146a932-b5a8-4aaf-8d94-2d7c107d5d51.png">

## Tested production build
<img width="1582" alt="Screenshot 2023-03-09 at 3 52 12 PM" src="https://user-images.githubusercontent.com/2374625/224155483-d2edca5d-7a80-41cc-97eb-d3e34ec9a7b8.png">

2023-03-09 23:10 UTC, tinahollygb commented on src/devtools/controller.ts
> +const isProd = process.env.NODE_ENV === "production";
What if we had something like:

```ts
const isChrome = typeof chrome !== 'undefined'
```

My concern with removing the dev build is that production builds take longer to build than dev, so I wouldn't want us to remove the ability to create a dev build.

I'd rather we retain the ability to build both and instead add a script like `serve:devtools` where we serve the devtools. Similarly for popup and options, we'd need a `serve:options` and `serve:popup` or maybe we can have a single webpack-dev-server run serve all 3. Or maybe we serve them all on the same server at the same host but at different paths, e.g. `/devtools.html`, `popup.html`, `options.html`.

2023-03-09 23:12 UTC, tinahollygb commented on src/devtools/controller.ts
> +  };
I wouldn't use mock data in the real app. This is why something like Storybook comes in handy. When a component is structured using presentational-container component architecture, and the features are passed into the main component, e.g. `<DevTools />` (which I think is just `<App />` right now, and probably needs to change), then we can mock it as needed.

2023-03-09 23:15 UTC, tinahollygb commented on src/devtools/controller.ts
> +const isProd = process.env.NODE_ENV === "production";
Regarding this, I see in the screenshot that the dev server hosts all 3, disregard that part.

2023-03-09 23:18 UTC, tinahollygb requested changes
I think we need the webpack-dev-server to work but I don't agree with the approach taken:

- I don't think we should disable dev builds as production takes too long. Can you restore that and instead check for `chrome`? 

Minor concerns:

- I don't think we should add hardcoded mock data into the source code. Do you think it's possible to re-architect it to not have such a dependency on `chrome` and allow us to pass in all dependencies via props? 

See inline comments for more info.

2023-04-04 13:20 UTC, bttf commented
@tinahollygb Just an update, definitely have ways to address your concerns. Thanks for the feedback. Just waiting for the dust to settle on visual editor updates and will tackle these as soon as that's done.

2023-08-04 22:14 UTC, bttf commented
This has gone stale. Deleting

2023-08-04 22:14 UTC, closed without merging